#!/bin/bash
set -e # Exit with nonzero exit code if anything failss

SEPARATOR="

"

if [ ! -f "CPP_PACKAGE_VERSION.txt" ]
then
    echo "CPP_PACKAGE_VERSION.txt not found."
    exit 1
fi

PACKAGE_VERSION=$(<CPP_PACKAGE_VERSION.txt)
PACKAGE_RELEASE_NOTES=$(<CPP_PACKAGE_RELEASE_NOTES.txt)
PACKAGE_URL="https://www.nuget.org/packages/Platform.$REPOSITORY_NAME.TemplateLibrary/$PACKAGE_VERSION"

TAG_BUFFER="$PACKAGE_VERSION"
NAME_BUFFER="[C++] $PACKAGE_VERSION"
PACKAGE_RELEASE_NOTES_STRING_BUFFER="$PACKAGE_URL$SEPARATOR$PACKAGE_RELEASE_NOTES"

publish-release.sh $REPOSITORY_NAME $TAG $GITHUB_TOKEN $DEFAULT_BRANCH $RELEASE_NAME $RELEASE_BODY
