#!/bin/bash

for subdirectory in ./*/
do
  cd $subdirectory;
  printf "Repository name: ${subdirectory}";
  default_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p');
  git pull origin ${default_branch};
  cd ..;
done;
