on:
  workflow_call:
    outputs:
      package_name:
        description: "The conan package name"
        value: ${{ jobs.get_conan_package_info.outputs.package_name }}
        
env:
  REPOSITORY_NAME: $(basename ${{ github.repository }})
        
jobs:
  get_package_info:
    uses: ./.github/workflows/get-cpp-package-info.yml
  get_conan_package_info:
    needs: [get_package_info]
    runs-on: ubuntu-latest
    outputs: 
      package_name: platform.$(echo ${{env.REPOSITORY_NAME}} | tr '[:upper:]' '[:lower:]')
    steps:
      - name: Get package name
        id: get_package_name
        run: |
          package_name="platform.$(echo ${{needs.get_package_info.outputs}} | tr '[:upper:]' '[:lower:]')"
          echo "package_name=${package_name}" >> $GITHUB_OUTPUT
